### ISSUE TITLE
The OAuth URLs don't respect different base_url's set in the config

### ISSUE THREAD

**Issue by cschuch** [exactonline/exactonline-api-ruby-client#48]
I'm a US user, and therefore have to use https://start.exactonline.com. Right now, `Elmas::OAuth.authorize_url` and `get_access_token` have the `.nl` address hard coded instead of using the `Elmas::Config.base_url` to construct the correct URL.

**Comment by Marthyn** [comment]
Good find, i'll fix that and release an updated version today!

**Comment by Marthyn** [comment]
So i fixed this in https://github.com/exactonline/exactonline-api-ruby-client/pull/49. But you also have to realize that this Oauth class is not really meant for production use, it's better to leave the Oauth authorization to the application you're using Elmas in. I am also not sure if it will work now since we've used the Dutch version of the HTML in the Oauth class. You might have to implement your own authorization implementation. I've tested this code with a Dutch base url only.

**Comment by cschuch** [comment]
Hi - sure, I'll check it out later today.

And no worries - we're mostly just using this to pull our own data for internal use in a few scripts, so nothing mission critical. Thanks for taking a look at this so quickly! I appreciate it, and I'll let you know later how the branch works out.

**Comment by Marthyn** [comment]
@cschuch I'm closing this issue, fix is available in version `2.4.0` and upwards
