### ISSUE TITLE
Auth does not work (in demo environment)

### ISSUE THREAD

**Issue by edwardmp** [exactonline/exactonline-api-ruby-client#58]
We are currently evaluating whether we want to use Exact Online. We want to test the API features first. However, we can't get auth to work in combination with this gem. We are using the Exact Online demo environment.

```
    Elmas.configure do |config|
      config.access_token = Elmas.authorize('user', 'pass').access_token
    end
```

Currently yields:
```
JSON::ParserError: 765: unexpected token at 'Bad Request'
/opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
/opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
/opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elmas-2.4.1/lib/elmas/oauth.rb:111:in `body'
/opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elmas-2.4.1/lib/elmas/response.rb:22:in `parsed'
/opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elmas-2.4.1/lib/elmas/response.rb:42:in `error_message'
/opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elmas-2.4.1/lib/elmas/response.rb:46:in `log_error'
/opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elmas-2.4.1/lib/elmas/response.rb:65:in `raise_and_log_error'
/opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elmas-2.4.1/lib/elmas/response.rb:10:in `initialize'
/opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elmas-2.4.1/lib/elmas/oauth.rb:18:in `new'
/opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elmas-2.4.1/lib/elmas/oauth.rb:18:in `authorize'
/opt/boxen/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/elmas-2.4.1/lib/elmas.rb:59:in `method_missing'
```

This should just work, right? Might it be that the demo environment does not work with the API somehow?

Maybe I am missing something, but isn't exact redirecting to the registered callback URL? Do we need to provide our own implementation for that?

**Comment by edwardmp** [comment]
So I did some debugging, and found the URL to which the user is normally redirected to give auth permission: 'https://start.exactonline.nl/api/oauth2/auth/?client_id=blabla&response_type=code&redirect_uri=https%3a%2f%2fwww.getpostman.com%2foauth2%2fcallback' and manually granted access. Everything worked fine after that.

Can someone explain to me what happened here?

**Comment by Marthyn** [comment]
@edwardmp As stated in the readme, the authentication methods we provide are very buggy and should not be dependent on. 

The thing you describe is something many people have encountered. 

The authorization code we wrote opens the sign in form and fills out the username/password and submits the form. If the authorization button appears it should be clicked with this method:
```
def allow_access(agent)
      form = agent.page.form_with(id: "PublicOAuth2Form")
      button = form.button_with(id: "AllowButton")
      agent.submit(form, button)
    end
```

The problem is though they might have changed the form for example. 

The most surefire way to make the gem work is build your own OATH2 logic, get a token and set it in the gem with:
```
Elmas.configure do |config|
  config.access_token = "your_token"
end
```

Because Exact does not support server to server communication this is unfortunate but necessary. You can read more about their OAUTH2 choices here: https://developers.exactonline.com/#OAuth/EOL_OAuth-Dev-OAuthImpleCases.htm%3FTocPath%3DAuthorization%2520(OAuth2)%7C_____3

**Comment by edwardmp** [comment]
@Marthyn 

Thanks for the response. Understand why it happens. weird that Exact "owns" this repository yet does not provide a proper authentication way beside OAUTH (which only makes sense for certain types of apps).

**Comment by Marthyn** [comment]
@edwardmp 

There has been an update to the Oauth class, maybe you could try the new 2.5.0 version?
