### ISSUE TITLE
Is Elmas thread safe?

### ISSUE THREAD

**Issue by srpouyet** [exactonline/exactonline-api-ruby-client#7]
Hi,

I was wondering if Elmas can be considered thread safe, since the access token and current division seem to be configured globally, e.g.:

```ruby
Elmas.configure do |config|
  config.access_token = Elmas.authorize(ENV['EXACT_USER_NAME'], ENV['EXACT_PASSWORD']).access_token
end
```

Cheers!

**Comment by Marthyn** [comment]
It's not thread safe because of that race condition indeed. You always have to make sure you authorize and set those 2 variables at this moment (and every ten minutes). Exact does not have an app token authorization system unfortunaly. Everything has to be done with OAUTH2. At Hoppinger we needed to directly send invoices from a website to Exact, without any user interface, therefore we let Mechanize authorize with our admin's username and password and allow access to the spefic app. 

Ideally we would just define an app_token and the division as an environment variable and load that into the config, but this is the only way so far i thought i could make it work.

If you have any other ideas please let me know, cause this is a part of the gem that bugs me.

**Comment by srpouyet** [comment]
Hey @Marthyn! We wrote a custom client for our app some time ago. We have to import invoices for different Exact Online customers into our application at the same time. We use Sidekiq for this, so it has to be threadsafe.

When a user authorizes our application for Exact Online, we store the OAuth2 token for this customer. When the access token expires, we request and store a new access token with the refresh token we stored earlier.

For every connection to Exact Online we initialize a new client instance with the access token we stored and set the division as needed. This way we can have many instances of clients running at the same time, using different accounts and pointing to different divisions.

Maybe for Elmas you could do something like:

```ruby
client = Elmas::Client.new(
  client_id: ENV['CLIENT_ID'], 
  client_secret: ENV['CLIENT_SECRET'], 
  access_token: some_access_token
)
# Optionally set the division, otherwise fallback to current division
client.division = 123456
# Then you can do
contact = Elmas::Contact.new(id: "23445", client: client)
# or
contact = client::Contact.new(id: "23445")
# or
contact = client.contacts.find(id: "23445")
```

**Comment by srpouyet** [comment]
I just came across this [blog post](http://blog.joncairns.com/2013/08/how-i-got-stung-by-the-twitter-gem-and-thread-safety/) about a similar thread safety issue with a previous version of the [Twitter gem](https://github.com/sferik/twitter), might be of use.

**Comment by srpouyet** [comment]
Hi, just a small update: I toyed around with Elmas last night and I think with this [change](https://github.com/srpouyet/exactonline-api-ruby-client/commit/b7053fbe40dc28357af74b99e78ca4a2d55baac1) thread safety is achieved. Best of all the gem stays backwards compatible. I'll do some additional testing and expect to open a PR sometime soon.

**Comment by Marthyn** [comment]
@srpouyet Super work! Closing this.

**Comment by korstiaan** [comment]
https://github.com/exactonline/exactonline-api-ruby-client/pull/51
